@WebApi_HostAddress = http://localhost:5236

GET {{WebApi_HostAddress}}/test/endpoint1?scheme=Scheme1
Accept: application/json

###

GET {{WebApi_HostAddress}}/test/endpoint1?scheme=Scheme2
Accept: application/json

###

GET {{WebApi_HostAddress}}/test/endpoint1
Accept: application/json

###

GET {{WebApi_HostAddress}}/test/endpoint1?scheme=SchemeThatDoesNotExist
Accept: application/json
